import type { Metadata } from "next"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div><h2>shop ki nav bar</h2>
        {children}
      </div>
  );
}
//html and body tag is only use in our main layout present in app otherwise it will give hydration error
